set mouse=a
set expandtab
set softtabstop=2
set tabstop=4
set shiftwidth=2
syn on
au BufNewFile,BufREad *.cu set filetype=c
au BufNewFile,BufREad *.cg set filetype=c
au BufNewFile,BufREad *.php set filetype=php
map <MiddleMouse> <Nop>
imap <MiddleMouse> <Nop>

autocmd FileType make setlocal noexpandtab
autocmd FileType python setlocal tabstop=4|set shiftwidth=4|set expandtab
au BufNewFile,BufRead *.frag,*.vert,*.fp,*.vp,*.glsl setf glsl 

